/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_reading_free(a: number): void;
export function reading_peak(a: number): number;
export function reading_error_ppm(a: number): number;
export function reading_log_probability(a: number): number;
export function reading_mass(a: number): number;
export function reading_charge(a: number): number;
export function reading_counts(a: number, b: number): void;
export function crible_mixed_radix(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number): void;
export function crible_heap(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function parse_thermo_raw(a: number, b: number, c: number, d: number): void;
export function __wbg_forest_free(a: number): void;
export function forest_edge_u(a: number, b: number): void;
export function forest_edge_v(a: number, b: number): void;
export function forest_edge_weight(a: number, b: number): void;
export function forest_edge_standard(a: number, b: number): void;
export function forest_degree(a: number, b: number): void;
export function forest_component_of(a: number, b: number): void;
export function forest_component_root(a: number, b: number): void;
export function forest_component_size(a: number, b: number): void;
export function forest_component_max_intensity(a: number, b: number): void;
export function forest_component_weight(a: number, b: number): void;
export function forest_component_root_mass(a: number, b: number): void;
export function forest_component_peak_mass(a: number, b: number): void;
export function forest_candidates(a: number): number;
export function forest_weights(a: number, b: number): void;
export function forest_cut_used(a: number): number;
export function forest_isolated(a: number): number;
export function forest_edge_count(a: number): number;
export function forest_component_count(a: number): number;
export function forest_grow(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function __wbg_persistenceanalysis_free(a: number): void;
export function persistenceanalysis_births(a: number, b: number): void;
export function persistenceanalysis_deaths(a: number, b: number): void;
export function persistenceanalysis_points_x(a: number, b: number): void;
export function persistenceanalysis_points_y(a: number, b: number): void;
export function persistenceanalysis_birth_indices(a: number, b: number): void;
export function persistenceanalysis_slope(a: number): number;
export function persistenceanalysis_integrated_mass(a: number, b: number): void;
export function persistenceanalysis_centroid_x(a: number, b: number): void;
export function __wbg_persistenceclassification_free(a: number): void;
export function persistenceclassification_kept_births(a: number, b: number): void;
export function persistenceclassification_discarded_deaths(a: number, b: number): void;
export function persistenceclassification_kept_count(a: number): number;
export function persistent_homology_0d_waves(a: number, b: number, c: number, d: number, e: number): number;
export function classify_persistence_0d(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number): number;
export function persistenceclassification_kept_deaths(a: number, b: number): void;
export function persistenceclassification_kept_points_x(a: number, b: number): void;
export function persistenceclassification_kept_points_y(a: number, b: number): void;
export function persistenceclassification_kept_indices(a: number, b: number): void;
export function persistenceclassification_kept_integrated_mass(a: number, b: number): void;
export function persistenceclassification_kept_centroid_x(a: number, b: number): void;
export function persistenceclassification_discarded_births(a: number, b: number): void;
export function __wbg_trimresult_free(a: number): void;
export function trimresult_points_x(a: number, b: number): void;
export function trimresult_points_y(a: number, b: number): void;
export function trimresult_kept_indices(a: number, b: number): void;
export function trimresult_total_count(a: number): number;
export function __wbg_trimhistogram_free(a: number): void;
export function trimhistogram_centres(a: number, b: number): void;
export function trimhistogram_counts(a: number, b: number): void;
export function trimhistogram_min(a: number): number;
export function trimhistogram_max(a: number): number;
export function trimhistogram_dropped(a: number): number;
export function trim_guess(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function trim_apply(a: number, b: number, c: number, d: number, e: number): number;
export function trim_histogram(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function trimresult_low_bound(a: number): number;
export function trimresult_high_bound(a: number): number;
export function trimresult_kept_count(a: number): number;
export function fkmd(a: number, b: number, c: number, d: number): void;
export function __wbg_radiodecision_free(a: number): void;
export function radiodecision_points_x(a: number, b: number): void;
export function radiodecision_points_y(a: number, b: number): void;
export function radiodecision_indices(a: number, b: number): void;
export function radiodecision_widths_ppm(a: number, b: number): void;
export function radiodecision_is_radio(a: number, b: number): void;
export function radiodecision_kept_count(a: number): number;
export function radiodecision_reference_ppm(a: number): number;
export function radiodecision_threshold_ppm(a: number): number;
export function anti_radio_guess_z(a: number, b: number, c: number, d: number, e: number): number;
export function anti_radio_filter(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): number;
export function compute(a: number, b: number): number;
export function add(a: number, b: number): number;
export function arrust(a: number, b: number, c: number): void;
export function add_scalar(a: number, b: number, c: number, d: number): void;
export function bench(a: number): number;
export function sieve(a: number): void;
export function zeros_matrix(a: number, b: number): void;
export function persistent_homology_0d(a: number, b: number, c: number, d: number, e: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
